# Generated by Django 4.2.3 on 2023-07-26 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('full_name', models.CharField(default='', max_length=50)),
                ('paused', models.BooleanField(default=False)),
                ('duration', models.TimeField()),
                ('when', models.DateTimeField()),
                ('flag', models.ImageField(default='white.png', upload_to='flag')),
                ('time_to_yellow', models.TimeField(default=datetime.time(0, 0))),
                ('time_to_red', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
