# Generated by Django 4.2.3 on 2023-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='timer',
            name='can_disconnect',
            field=models.BooleanField(default=False),
        ),
    ]
