# Generated by Django 4.2.3 on 2023-12-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_servertimezone_timer_can_disconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_tfz',
            field=models.BooleanField(default=False),
        ),
    ]
